# Generated by Django 5.0.2 on 2024-03-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='wing',
            field=models.CharField(blank=True, choices=[('ARMY', 'Army'), ('NAVAL', 'Naval'), ('AIR_FORCE', 'Air Force')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userreport',
            name='reason',
            field=models.CharField(choices=[('SPAM', 'Spam'), ('INAPPROPRIATE', 'Inappropriate')], max_length=13),
        ),
    ]
