# Generated by Django 5.0.2 on 2024-03-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_comment_id_alter_notification_id_alter_post_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreport',
            name='reason',
            field=models.CharField(choices=[('SPAM', 'Spam'), ('INAPPROPRIATE', 'Inappropriate')], max_length=13),
        ),
    ]
